# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- test-ci-*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Stage 0 (Docker)
  jobs:  
  
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
     - task: Docker@2
      displayName: Build Debug
      condition: succeededOrFailed()
      inputs:
        containerRegistry: 'p3bankacr_connection'
        repository: 'ng-debug'
        command: 'build'
        Dockerfile: 'Dockerfile-debug'
        tags: |
          $(Build.BuildId)
          debug
          latest
        
    - task: Docker@2
      displayName: Push Debug
      condition: and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        containerRegistry: 'p3bankacr_connection'
        command: 'push'
        repository: 'ng-debug'
        tags: |
          $(Build.BuildId)
          debug
          latest

  - job: Build
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build Release
      inputs:
        containerRegistry: 'p3bankacr_connection'
        repository: 'ng-release'
        command: 'build'
        Dockerfile: 'Dockerfile'
        tags: |
          $(Build.BuildId)
          release
          latest

    - task: Docker@2
      displayName: Push Release
      condition: and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        containerRegistry: 'p3bankacr_connection'
        command: 'push'
        repository: 'ng-release'
        tags: |
          $(Build.BuildId)
          release
          latest
          