# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build Release
      inputs:
        repository: 'ng-release'
        command: 'build'
        Dockerfile: 'Dockerfile'

    - task: Docker@2
      displayName: Push Release
      condition: ne(variables['Build.Reason'], 'PullRequest')
      inputs:
        containerRegistry: 'p3bankacr_connection'
        command: 'push'
        repository: 'ng-release'
        tags: |
          $(Build.BuildId)
          release
          latest

    - task: Docker@2
      displayName: Build Debug
      condition: succeededOrFailed()
      inputs:
        repository: 'ng-debug'
        command: 'build'
        Dockerfile: 'Dockerfile-debug'
        
    - task: Docker@2
      displayName: Push Debug
      condition: ne(variables['Build.Reason'], 'PullRequest')
      inputs:
        containerRegistry: 'p3bankacr_connection'
        command: 'push'
        repository: 'ng-debug'
        tags: |
          $(Build.BuildId)
          debug
          latest