# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push Release
      inputs:
        containerRegistry: 'p3bankacr_connection'
        repository: 'ng-release'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          $(Build.BuildId)
          release
          latest
    - task: Docker@2
      displayName: Build and Push Debug
      inputs:
        containerRegistry: 'p3bankacr_connection'
        repository: 'ng-debug'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile-debug'
        tags: |
          $(Build.BuildId)
          debug
          latest